module.exports = {
  apps: [
    {
      name: 'veruspulse-web',
      script: 'npm',
      args: 'start',
      cwd: '/var/www/veruspulse',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/var/log/veruspulse/web-error.log',
      out_file: '/var/log/veruspulse/web-out.log',
      log_file: '/var/log/veruspulse/web-combined.log',
      time: true,
    },
    {
      name: 'oink-staking-scanner',
      script: 'scripts/standalone-staking-scanner.js',
      cwd: '/var/www/veruspulse',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/veruspulse/oink-staking-error.log',
      out_file: '/var/log/veruspulse/oink-staking-out.log',
      log_file: '/var/log/veruspulse/oink-staking-combined.log',
      time: true,
    },
    {
      name: 'oink-ultra-scanner',
      script: 'scripts/ultra-fast-scanner.js',
      cwd: '/var/www/veruspulse',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/veruspulse/oink-ultra-error.log',
      out_file: '/var/log/veruspulse/oink-ultra-out.log',
      log_file: '/var/log/veruspulse/oink-ultra-combined.log',
      time: true,
    },
    {
      name: 'oink-hybrid-scanner',
      script: 'scripts/hybrid-on-demand-scanner.js',
      cwd: '/var/www/veruspulse',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/veruspulse/oink-hybrid-error.log',
      out_file: '/var/log/veruspulse/oink-hybrid-out.log',
      log_file: '/var/log/veruspulse/oink-hybrid-combined.log',
      time: true,
    },
  ],
};
