console.log('📊 Verus Block Types Analysis:');
console.log('');
console.log('You said: Verus is 50/50 PoS/PoW');
console.log('');
console.log('From our scans:');
console.log('   - We scan ~240,000 blocks per year');
console.log('   - PoS blocks found: ~240,000 (validationtype="stake")');
console.log('   - PoW blocks would be the rest');
console.log('');
console.log('Implications:');
console.log("   If it's 50/50 PoS/PoW:");
console.log('   - Expected PoS: ~240,000 / 2 = 120,000 blocks');
console.log('   - Expected PoW: ~120,000 blocks');
console.log('');
console.log('But we found:');
console.log('   - PoS blocks: ~240,000 (validationtype="stake")');
console.log('   - This suggests:');
console.log('     - The block time is ~30 seconds (not 60)');
console.log('     - OR the year is actually 480k blocks, not 240k');
console.log('     - OR PoW blocks are not marked differently');
console.log('');
console.log('Let me check if PoW blocks have different validationtype...');
