console.log('Why the 2020 scan failed to capture caribu66@ stakes:');
console.log('');
console.log('The Problem: Block numbers do NOT correspond to calendar years!');
console.log('');
console.log('What we THOUGHT:');
console.log('   Block 1,299,328 = December 2020');
console.log('   Block 2,500,000 = December 2025');
console.log('   = 5 years of blocks');
console.log('');
console.log('What we ACTUALLY GOT:');
console.log('   Block 1,299,328 = December 2020');
console.log('   Block 2,500,000 = April 2023 (only 2.5 years!)');
console.log('   = Only 2.5 years of blocks');
console.log('');
console.log('Why this happened:');
console.log('   - We assumed ~240k blocks per year');
console.log('   - We scanned 1.2 million blocks (5 x 240k)');
console.log('   - But block production slowed down or was different');
console.log('   - So 1.2 million blocks only covered 2.5 calendar years');
console.log('');
console.log('Solution: Scan from block 2,500,000 to current tip');
console.log('   This will cover April 2023 to October 2025');
console.log('   This is what the current scanner is doing!');
