name: E2E A11y (Playwright + axe)

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  e2e-a11y:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Build Next.js
        run: npm run build

      - name: Start Next.js (prod)
        run: |
          nohup npm run start:prod >/dev/null 2>&1 &

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run Playwright a11y contrast tests (light + dark)
        run: npx playwright test tests/e2e/a11y-contrast.spec.ts --reporter=list

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Stop server
        if: always()
        run: |
          kill $(lsof -t -i:3000) || true
